// <auto-generated />
namespace DataAccesLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class message_add_IsRead : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(message_add_IsRead));
        
        string IMigrationMetadata.Id
        {
            get { return "202107122015244_message_add_IsRead"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
